### ISSUE TITLE
Assert method input

### ISSUE THREAD

**Issue by simplicbe** [simplic-systems/simplic-utilities#1]
I think we should assert the input of the methods:

https://github.com/simplic-systems/simplic-utilities/blob/dev/src/Simplic.Utilities/TemplateParser/Impl/DefaultParser.cs#L29

**Comment by yvz5** [comment]
It doesnt give any error if the input text is empty. I think it is the responsibility of the caller to check if the input string is empty.

**Comment by simplicbe** [comment]
Empty is not a problem, but null. Because throwing a `ArgumentNullException` is more specific in the stacktrace. E.g.: `if (input == null) throw new ArgumentNullException(nameof(input));`

**Comment by simplicbe** [comment]
Done with #dd54704 thanks.
