### ISSUE TITLE
Should we use PlugIn or Plugin

### ISSUE THREAD

**Issue by simplicbe** [simplic-systems/simplic-utilities#7]
I'm currently not sure whether to use `PlugIn` or `Plugin`. In the past I've preferred using `PlugIn`.

**Comment by yvz5** [comment]
"Plugin" has become a standalone word. It consists of two words, but it is used as one word today. I would prefer "Plugin". Wordpress, mozilla and many others call it Plugin.

**Comment by simplicbe** [comment]
I agree.
